### ISSUE TITLE
cant show the placeholders 

### ISSUE THREAD

**Issue by llt12213** [yapzhenyie/GadgetsMenu#888]
it's a little bug i think
server ver:paper1.17.1
plugin ver:4.5.4
my players tell me that main menu's place holders can not me shown,like this

[![IkHP1g.png](https://z3.ax1x.com/2021/11/03/IkHP1g.png)](https://imgtu.com/i/IkHP1g)

idk how to fix it or is here some wrong of messgaes.yml?
help pls
also u can use chinese to tell me :)

**Comment by yapzhenyie** [comment]
Please refer to the sample below and change your placeholder accordingly.
`{MYSTERY_DUST}` should change to `{COST}`
'{SURPLUS_MYSTERY_DUST}' should change to `{COST_LEFT}`
```
  Not-Enough-Mystery-Dust:
    Lore:
    - ''
    - '&cClick to craft for &b{COST} &cMystery Dust!'
    - '&cYou need &b{COST_LEFT} &cmore mystery dust!'
    Play-Sound:
      Enabled: true
      Sound: ENTITY_ENDERMAN_TELEPORT
  Enough-Mystery-Dust-To-Craft-Mystery-Box:
    Lore:
    - ''
    - '&7Cost: &a{COST} &7Mystery Dust'
    - '&aClick to craft!'
    Play-Sound:
      Enabled: true
      Sound: ENTITY_EXPERIENCE_ORB_PICKUP
  Not-Enough-Mystery-Dust-To-Craft-Mystery-Box:
    Lore:
    - ''
    - '&7Cost: &a{COST} &7Mystery Dust'
    - '&cNot enough Mystery Dust!'
    Play-Sound:
      Enabled: true
      Sound: ENTITY_ENDERMAN_TELEPORT
```
