### ISSUE TITLE
Adding button to mainmenu

### ISSUE THREAD

**Issue by DisguisedTurtlee** [yapzhenyie/GadgetsMenu#910]
Hey, im working on making a MAIN panel to my server using GUI+, i added the gadgetsmenu to the the main panel, but i want to add a button the gmenu when i press it it gets me bach to the MAIN panel

tytytytytyty

**Comment by yapzhenyie** [comment]
You can modify the go back button in config.yml file.

```
# When player clicks 'Go Back' button will execute these commands.
# If you enabled this option, it won't open the main menu of GadgetsMenu.
# Placeholders: {PLAYER}
Back-To-Main-Menu:
  Execute-Commands:
    Enabled: false
    Commands:
    - cc open menu.yml {PLAYER}
```
