### ISSUE TITLE
Custom particles, cloaks, gadgets and miniature particles

### ISSUE THREAD

**Issue by Sm1rkyea** [yapzhenyie/GadgetsMenu#989]
Hello,

I'd like to suggest an option for implementing custom and original particles, cloaks and gadgets, if such a feature doesn't already exist. For example, already mentioned custom cosmetics could be added through custom code or directly from YML plugin configuration.

Here's an example of how it could work for custom Cloak added via YML:

```
Cloak:
    Cloak: VORTEX/WINGS/TERRESTRIAL/CLASSIC
    Type: Type of the wings
    Particles:
        - PARTICLE:ID
        - PARTICLE:ID
    Walk: true/false
```

Cloak would define the overall structure or style, type would define the shape of the cloak, particles are specifying the IDs of particle effects that are used in our cloak and walk will provide an option to display cloak while player is walking or not.

This is, of course just an example, additional options and customizations can be more user-friendly and flexible.

Thanks, Smirkyea.
